config/routes.rb
Rails.application.routes.draw do
  resource :dashboard, only: [:show]
  resource :session, only: [:create, :destroy, :show]
  resource :search, only: [:show]
  resources :starts, only: [:new, :create, :show] do
    resources :additions, only: [:create, :destroy], shallow: true
  end
  resources :users, except: [:new, :destroy]

  resources :follows, only: [:destroy]
  post 'follows/:id', to: 'follows#create'

  get '/usernames', to: 'root#new'
  get '/prompt', to: 'starts#prompt', as: :prompt

  root "root#show", via: :get
end

app/models/addition.rb
class Addition < ActiveRecord::Base
  validates :addition_text, presence: true, length: {maximum: 140}
  validates_presence_of :user_id, :start_id

  belongs_to :user
  belongs_to :start
end

app/models/dashboard.rb
class Dashboard
  def initialize(user)
    @user = user
  end

  def get_starts
    unless @start
      followees = @user.follows

      ids = (
      @user.starts +
        @user.addition_starts +
        followees.map { |follow|
          follow.followee.starts + follow.followee.addition_starts
        }
      ).flatten.uniq

      @start = Start.where(id: ids)
    else
      @start
    end
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  validates_presence_of :user_id, :user_followed_id

  belongs_to :user
  belongs_to :followee, class_name: 'User', foreign_key: :user_followed_id
end

app/models/prompt.rb
require 'bazaar'

class Prompt
  def self.get_array
    [Bazaar.item, Bazaar.super_adj, Bazaar.super_item]
  end

  def self.get_item
    [Bazaar.item, Bazaar.super_adj, Bazaar.super_item].sample
  end
end

app/models/search.rb
class Search
  attr_reader :string

  def initialize(string)
    @string = string
  end

  def starts
    @starts ||= Start.where("title ILIKE '%#{@string}%'")
  end

  def users
    @users ||= User.where("username ILIKE '%#{@string}%'")
  end
end

app/models/start.rb
class Start < ActiveRecord::Base
  validates_presence_of :title, :story_text, :user_id
  validates_length_of :story_text, maximum: 140

  belongs_to :user
  has_many :additions

  default_scope {order(updated_at: :desc)}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true
  validates :email, presence: true

  has_many :starts
  has_many :additions
  has_many :follows
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  def addition_starts
    addition = Addition.where(user_id: id).map{|addition| addition.start_id unless addition.start.user_id == id}.uniq

    Start.where(id: addition)
  end
end

app/controllers/additions_controller.rb
class AdditionsController < ApplicationController
  def create
    @start = Start.find(params[:start_id])

    @addition = @user.additions.build(addition_params)

    @addition.start_id = @start.id

    @addition.addition_number = @start.additions.count + 1

    if @addition.save
      @addition.start.update(updated_at: Time.now)

     render json: [@addition, @addition.user.username, @addition.user.id]
    else
      raise
    end
  end

  def destroy
    @addition = Addition.find(params[:id])

    if @addition.start.user_id == @user.id
      @addition.destroy
    else
      raise 'not authorized to delete'
    end

    render json: @addition
  end

  private

  def addition_params
    params[:addition].permit(:addition_text)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @dashboard = Dashboard.new(current_user)

    respond_to do |format|
      format.html
      format.json { render json: @dashboard.get_starts}
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    @follow = Follow.new(
      user_id: current_user.id,
      user_followed_id: params[:id]
    )

    raise unless @follow.save

    render json: @follow
  end

  def destroy
    @follow = Follow.find_by(user_id: current_user.id, user_followed_id: params[:id])

    raise unless @follow

    @follow.destroy

    render json: @follow
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  layout 'login'
  skip_before_filter :require_authentication!

  def show
    redirect_to "/dashboard" if logged_in?

    @user = User.new
  end

  def new
    @register_check = User.all.collect {|user| user.username}

   render json: @register_check
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search = Search.new(params[:search])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_authentication!

  def create
    @user = User.find_by(
      username: params[:user][:username]
    )

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to '/dashboard'
    else
      session[:user_id] = nil
      redirect_to root_path, alert: 'Username or password is incorrect!'
    end
  end

  def show
    destroy
  end

  def destroy
    reset_session
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/starts_controller.rb
class StartsController < ApplicationController
  before_filter :require_authentication!

  def new
    @start = Start.new
  end

  def create
    @start = Start.new(start_params.merge({user_id: current_user.id}))

    if @start.save
      redirect_to dashboard_path, notice: "Story '#{@start.title}' created!"
    else
      flash[:notice] = @start.errors.full_messages
      render :new
    end
  end

  def show
    @additions = Start.find(params[:id]).additions

    @usernames = @additions.collect {|addition|
      user = User.find(addition.user_id)

      [addition.id, user.id, user.username]
    }

    render json: [@additions, @usernames]
  end

  def prompt
    render json: Prompt.get_array
  end

  private

  def start_params
    params[:start].permit(:title, :story_text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_authentication!, except: [:create]

  def index
    @user = User.find(session[:user_id])

    render json: @user.id
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'Your account has been successfully created.'
    else
      redirect_to root_path, alert: 'Sorry, your account could not be created.'
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to edit_user_path, notice: 'Your profile has been updated!'
    else
      flash[:notice] = 'oopsie'
      render :edit
    end
  end

  def show
    @profile_user = User.find(params[:id])
  end

  private

  def user_params
    params[:user].permit(:email, :password, :password_confirmation, :username, :avatar)
  end
end

app/helpers/additions_helper.rb
module AdditionsHelper
  def get_new_addition
    addition ||= Addition.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def random_story
    start = Start.all.sample
    if start
      sample_text = start.story_text
      start.additions.each { |addition|
        sample_text = sample_text + ' ' + addition.addition_text
      }
      sample_text
    else
      sample_text = 'i found the cure to growing older'
    end
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
  def show_follow(user)
    if user.id == current_user.id
      ''
    elsif Follow.find_by(user_id: current_user.id, user_followed_id: user.id)
      button_to 'following', follow_path(user), id: follow_path(user), class: 'button followed-button'
    else
      button_to 'follow', follow_path(user), id: follow_path(user), class: 'button follow-button'
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <div class="header-background">
    <div class="header-wrapper">
      <%= link_to 'TELLTALES', root_path, class: "highlight-text logo" %>
      <span class="dropdown-button"><%= image_tag 'menu-icon.png', class: 'header-icon' %></span>
      <span class="search-button"><%= image_tag 'search.png', class: 'header-icon' %></span>
      <span class="greeting">Welcome, <a href='/users/<%= user.id %>'><%= user.username %></a></span>
    </div>
  </div>

  <div class="search">
    <%= form_tag(search_path, method: "get") do %>
      <%= text_field_tag :search, '', class: "textfield" %>
      <%= submit_tag "Search", class: "button" %>
    <% end %>
  </div>

  <div class="header-dropdown-menu">
    <ul class="dropdown-list">
      <li><%= link_to 'New Story', new_start_path %></li>
      <li class="small-greeting"><a href='/users/<%= user.id %>'>My Profile</a></li>
      <li>My Stories</li>
      <li><%= link_to 'Account Settings', edit_user_path(current_user) %></li>
      <li><%= link_to "Logout", session_path, :method => :delete %></li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Telltales</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1.0">
</head>
<body data-controller="<%=controller_name%>" data-action="<%=action_name%>">

<%= render partial: 'layouts/header', locals: {user: @user} %>

<div class="wrapper">

  <% if flash[:notice] %>
    <p class='flash'><%= flash[:notice] %></p>
  <% end %>

  <%= yield %>
</div>

<div class="footer">
  <%= link_to image_tag('twitter.gif', class: 'icon'), 'https://twitter.com/Savannahdworth' %>

  Website by <span class="highlight-text">Savannah Worth</span>
</div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Telltales</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1.0">
</head>
<body>

  <% if flash[:notice] %>
    <p class='flash'><%= flash[:notice] %></p>
  <% end %>
  <%= yield %>

<div class="footer">
  <%= link_to image_tag('twitter.gif', class: 'icon'), 'https://twitter.com/Savannahdworth' %>

  Website by <span class="highlight-text">Savannah Worth</span>
</div>

</body>
</html>